//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace osm2mssql.InfoDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tNode
    {
        public tNode()
        {
            this.tNodeTag = new HashSet<tNodeTag>();
        }
    
        public long Id { get; set; }
        public System.Data.Spatial.DbGeography location { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
    
        public virtual ICollection<tNodeTag> tNodeTag { get; set; }
    }
}
