//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace osm2mssql.InfoDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tTagType
    {
        public tTagType()
        {
            this.tNodeTag = new HashSet<tNodeTag>();
        }
    
        public int Typ { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<tNodeTag> tNodeTag { get; set; }
    }
}
